name: Build & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:
  build:
      permissions:
        id-token: write # To sign the provenance.
        contents: write # To upload assets to release.
        actions: read # To read the workflow path.
      strategy:
        matrix:
          os:
            - linux
            - windows
            - darwin
          arch:
            - amd64
            - arm64
      uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
      with:
        go-version: 1.22
        config-file: .slsa-goreleaser/${{matrix.os}}-${{matrix.arch}}.yml